name: Run Tests

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl https://get.modular.com | MODULAR_AUTH=${{ secrets.MODULAR_AUTH }} sh -
          modular auth ${{ secrets.MODULAR_AUTH }}
          modular install mojo
          pip install .
      - name: Integration Tests
        run: |
          export MODULAR_HOME="/home/runner/.modular"
          export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"

          # Tests that do not fail
          pytest example/tests/mod_b

          # Tests that should fail
          if pytest example/tests/mod_a ; then
            echo "This tests should fail"
            exit 1
          fi

          # Test should fail becuase I am passing options for checking warnings
          rm -rf ~/.modular/.mojo_cache
          if pytest -W error example/tests/test_warning.mojo ; then
            echo "This tests should fail"
            exit 1
          fi

          # Test should not fail becuase I am not checking for warning
          rm -rf ~/.modular/.mojo_cache
          pytest example/tests/test_warning.mojo

