name: Run Tests

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl https://get.modular.com | sh -
          modular auth ${{ secrets.MODULAR_AUTH }}
          modular install --install-version 24.4.0 mojo
          pip install .
      - name: Integration Tests
        run: |
          export MODULAR_HOME="/home/runner/.modular"
          export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"
          export PYTHONPATH=/home/runner/work/mojo-pytest/mojo-pytest/example_src
          make test
