name: Run Tests

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: pytest-mojo

      - name: Integration Tests
        shell: bash -el {0}
        run: |
          conda info
          export PYTHONPATH=/home/runner/work/mojo-pytest/mojo-pytest/example_src
          make test
