name: Run Tests

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl https://get.modular.com | MODULAR_AUTH=${{ secrets.MODULAR_AUTH }} sh -
          modular auth ${{ secrets.MODULAR_AUTH }}
          modular install --install-version 24.1.0 mojo

          pip install .
      - name: Integration Tests
        run: |
          export MODULAR_HOME="/home/runner/.modular"
          export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"

          # check test collection (this count needs to be updated manually when tests are updated)
          pytest | grep "collected 17 items"

          # Tests that do not fail
          pytest example/tests/mod_b

          # Tests that should fail
          if pytest example/tests/mod_a ; then
            echo "expected pytest exit code 0"
            exit 1
          fi

          # Test should fail because I am passing options for checking warnings
          rm -rf ~/.modular/.mojo_cache
          if pytest -W error example/tests/test_warning.mojo ; then
            echo "expected pytest exit code 0"
            exit 1
          fi

          # Test should not fail because I am not checking for warning
          rm -rf ~/.modular/.mojo_cache
          pytest example/tests/test_warning.mojo

          # Test should fail because debug_assert is enabled
          rm -rf ~/.modular/.mojo_cache
          if pytest --mojo-assertions example/tests/test_debug_assert.mojo; then
            echo "expected pytest exit code 0"
            exit 1
          fi
